language: R
cache: packages

apt_packages:
  - libxml2-dev

r_github_packages:
  - hadley/emo

notifications:
  email:
    recipients:
      - jensen_303@hotmail.com
    on_success: never
    on_failure: always
