language: R
cache: packages

apt_packages:
  - libxml2-dev

install:
  - R -e "devtools::install_github('hadley/emo')"

r_github_packages:
  - hadley/emo

notifications:
  email:
    recipients:
      - jensen_303@hotmail.com
    on_success: never
    on_failure: always
